### ISSUE TITLE
Map not rendering (directory 3 & 4)

### ISSUE THREAD

**Issue by nakitamccool** [Code-Institute-Solutions/GoogleMaps#1]
Map will render if you place the following style at the bottom of your css file:
div#map{
    min-height: 360px;
}

I've checked the solution code for directory 3 & 4, map does not render. No js errors in console so it is a styling issue:
https://github.com/Code-Institute-Solutions/GoogleMaps/tree/master/03-rendering_the_map
https://github.com/Code-Institute-Solutions/GoogleMaps/tree/master/04-adding_markers_to_the_map

I've checked the solution code for directory 5 and map does render. This lesson covers taking your internal js and putting it into an external js file. No css style for map here in custom.css but map does render. 
https://github.com/Code-Institute-Solutions/GoogleMaps/tree/master/05-moving_the_code_into_its_own_script

Suggest we add a note in the LMS with short term fix of adding css style and then update the repo. LT, we may want to add the fix into the video. 

Will discuss in the 10.30 stand-up.

**Comment by nakitamccool** [comment]
@aaronsnig501 last time we talked about this in the stand up you wanted to do a quick review of the code. Have you had a chance to?

I'd like to incorporate the fix soon, so let me know if you're happy for me to go ahead. 

Thanks!

**Comment by nakitamccool** [comment]
@aaronsnig501 Can I go ahead and incorporate the fix for this? Thanks

**Comment by aaronsnig501** [comment]
@nakitamccool Wow... sorry... this completely managed to get passed me! You can go ahead and implement the fix. The only reason that I wanted to review it was to see how quickly it would be update the videos. We can probably leave the video as is for now, but we'll want to create a card on Trello to update this video ASAP
